### ISSUE TITLE
Layout bug when pressing Add to Favorites

### ISSUE THREAD

**Issue by Neraverin** [fess986/cinema-js-native-adv-lvl#48]
Текущее поведение

1. нажимаешь на Add to Favorites или другую аналогичную кнопку
2. картинка резко сдвигается вниз, а потом поднимается вверх
3. нажать быстро на 2 кнопки последовательно невозможно - второй клик приходится на картинку

Ожидаемое поведение
1. Картинку не дергает и можно быстро нажать на 2-3 кнопки.

**Comment by fess986** [comment]
resolved by 203990247ff4434f07085125a09c19cfbf4070f9
