### ISSUE TITLE
Top menu buttons don't work when pressing on number

### ISSUE THREAD

**Issue by Neraverin** [fess986/cinema-js-native-adv-lvl#50]
Текущее поведение
1. При наведении на кнопки основного меню, они темнеют. При этом темнеет не только текст, но и число справа. Такое поведение создает ощущение, что это единый элемент и что я могу нажать на цифру
2. Нажатие на цифру ничего не делает

Ожидаемое поведение
1. Нажатие на цифру аналогично нажатию на сам текст

**Comment by fess986** [comment]
resolved by c0eef36095c4bb377bcf3254c41883711c772db3
