### ISSUE TITLE
Move logic of `Most comended films` to Component

### ISSUE THREAD

**Issue by fess986** [fess986/cinema-js-native-adv-lvl#6]
# Refactoring... 
message1
## test message h2
message2

- [x] Move logic of `Most reccomended films` to Component
- [x] The end

![need to fix](https://user-images.githubusercontent.com/93880664/186204393-08d4f6da-a1ce-4a60-ab57-5f3b4f4d6796.PNG)

**Comment by Fess986master** [comment]
**I belive, that U can do it!**
